import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/ui/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en">
      <body className="min-h-full flex flex-col ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
