import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/ui/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en">
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="ml-50 mr-50 mt-10">
          {children}
        </div>
      </body>
      
    </html>
  );
}
